### ISSUE TITLE
ERROR in ./public/app/bootstrap.js

### ISSUE THREAD

**Issue by amejiarosario** [jgodi/angular2-fullstack-starter#10]
after `npm i`, I get:

```
ERROR in ./public/app/bootstrap.js
Module build failed: Error: eslint-config-bullhorn/rules/best-practices:
    Configuration for rule "no-labels" is invalid:
    Value "2,[object Object]" has more items than allowed.

Referenced from: eslint-config-bullhorn/legacy
Referenced from: eslint-config-bullhorn/base
Referenced from: bullhorn/angular2
Referenced from: /Users/admejiar/tmp/angular2-fullstack-starter/.eslintrc
    at validateRuleOptions (/Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-validator.js:102:15)
    at /Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-validator.js:148:13
    at Array.forEach (native)
    at Object.validate (/Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-validator.js:147:35)
    at load (/Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-file.js:390:19)
    at /Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (/Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-file.js:309:28)
    at load (/Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-file.js:395:22)
    at /Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-file.js:326:36
 @ multi app

ERROR in ./public/app/vendor.js
Module build failed: Error: eslint-config-bullhorn/rules/best-practices:
    Configuration for rule "no-labels" is invalid:
    Value "2,[object Object]" has more items than allowed.

Referenced from: eslint-config-bullhorn/legacy
Referenced from: eslint-config-bullhorn/base
Referenced from: bullhorn/angular2
Referenced from: /Users/admejiar/tmp/angular2-fullstack-starter/.eslintrc
    at validateRuleOptions (/Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-validator.js:102:15)
    at /Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-validator.js:148:13
    at Array.forEach (native)
    at Object.validate (/Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-validator.js:147:35)
    at load (/Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-file.js:390:19)
    at /Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (/Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-file.js:309:28)
    at load (/Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-file.js:395:22)
    at /Users/admejiar/tmp/angular2-fullstack-starter/node_modules/eslint/lib/config/config-file.js:326:36
```

**Comment by jgodi** [comment]
I will have to update this soon, it is severely out of date. I will try to get to it next week!
